services:
  app:
    build:
      context: ..
      dockerfile: docker/app/dockerfile
    restart: always
    volumes:
      - /root/IaC-server:/IaC-server
      - /root/IaC_user_workspace:/root/IaC_user_workspace # map user workspace
    #environment:
    #  - http_proxy=http://10.3.62.5:3128
    #  - https_proxy=http://10.3.62.5:3128
    #  - no_proxy=localhost,127.0.1,::1,queue_worker,redis,mongodb,10.38.26.25
    ports:
      - "8000:8000"

  queue_worker:
    build:
      context: ..
      dockerfile: docker/queue_worker/dockerfile
    restart: always
    volumes:
      - /root/IaC-server:/IaC-server
      - /root/IaC_user_workspace:/root/IaC_user_workspace
    #environment:
    #  - http_proxy=http://10.3.62.5:3128
    #  - https_proxy=http://10.3.62.5:3128
    #  - no_proxy=localhost,127.0.1,::1,app,redis,mongodb,10.38.26.25

  redis:
    image: redis:latest
    restart: always

  mongodb:
    image: mongo:latest
    restart: always
