version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - /root/IaC-server:/app/IaC-server
    ports:
      - "8000:8000"

  queue_worker:
    build: ./queue_worker
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"