services:
  app:
    build:
      context: ..
      dockerfile: docker/app/dockerfile
    volumes:
      - /root/IaC-server:/IaC-server
    ports:
      - "8000:8000"

  queue_worker:
    build:
      context: ..
      dockerfile: docker/queue_worker/dockerfile
    volumes:
      - /root/IaC-server:/IaC-server

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
