FROM python:3.10

WORKDIR /IaC-server

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD ["huey_consumer", "app.core.queue.factories.huey_task.huey", "--logfile=./log/queue.log"]

