FROM python:3.10

WORKDIR /IaC-server

RUN pip install --no-cache-dir --upgrade -r /IaC-server/requirements.txt

CMD ["huey_consumer", "app.core.queue.factories.huey_task.huey", "--logfile='/IaC-server/log/queue.log'"]